# site variables
title: Rand Asswad
description: >- # appears on homepage and in google search results 
  I'm a Masters student based in France, specializing in **applied mathematics** 
  and **theoretical computer science**.

  I am passionate about mathematics and math-adjacent domains,
  and am interested in pursuing a career in research.
baseurl: ""
url: ""

# sass config
sass:
  sass_dir: _sass
  style: compressed

# jekyll plugins
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: "sections"
    values:
      title: NewSection
      order: 10
      active: false

collections:
  - sections

# disable rouge to use hljs
kramdown:
  syntax_highlighter_opts:
    disable : true