# site variables
title: Rand Asswad
meta_description: | # appears in search engines preview
  Rand Asswad is an engineer in applied mathematics and computer science,
  specialized in AI and mathematical modeling.
description: | # appears on homepage
  I'm a Master's student based in France, specialized in **mathematics**, 
  **theoretical computer science**, and **numerical analysis**.

  I am passionate about mathematics and math-adjacent domains,
  and am interested in pursuing a career in research.
baseurl: ""
url: ""

# Google Analytics measurements ID
google_analytics: G-S3FZD64MJT

# sass config
sass:
  sass_dir: _sass
  style: compressed

# jekyll plugins
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: "sections"
    values:
      title: NewSection
      order: 10
      active: false

collections:
  - sections

# disable rouge to use hljs
kramdown:
  syntax_highlighter_opts:
    disable : true