# site variables
title: Rand Asswad
description: >- # appears on homepage and in google search results 
  I'm a Masters student based in France, specializing in applied mathematics 
  and theoretical computer science.

  I am passionate about mathematics and math-adjacent domains,
  and am interested in persuing a career in research.
baseurl: ""
url: ""

# sass config
sass:
  sass_dir: _sass
  style: compressed

# jekyll plugins
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: "sections"
    values:
      name: NewSection
      order: 10
      bgcolor: "#000"
      active: false

collections:
  - sections
