# site variables
title: Rand Asswad
description: | # appears in search engines preview (keep it under 120 chars)
  Rand Asswad is an engineer in applied mathematics and computer science,
  specialized in AI and mathematical modeling.
baseurl: ""
url: ""

# site theme definition
# terminology: https://visme.co/blog/wp-content/uploads/2016/09/website23-1024x512.jpg
theme:
  darker: "#25274D"
  dark:   "#464866"
  grey:   "#AAABB8"
  light:  "#29648A"
  bright: "#2E9CCA"

# jekyll collections
collections:
  - sections

# sass config
sass:
  sass_dir: _sass
  style: compressed

# static files
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: "sections"
    values:
      title: NewSection
      order: 10
      active: false

# jekyll plugins
plugins:
  - jekyll-minifier

# minifier settings
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

# Google Analytics measurements ID
google_analytics: G-S3FZD64MJT