name: build and deploy jekyll to pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    # use NPM for JavaScript runtime
    - name: install node
      uses: actions/setup-node@v3
    # cache Gems
    - name: cache ruby gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # build and deploy to Github
    - name: build and deploy jekyll
      uses: jeffreytse/jekyll-deploy-action@v0.3.1
      with:
        provider: 'github'
        token: ${{ secrets.GITHUB_TOKEN }}
        cname: 'rand-asswad.xyz'